# Generated by Django 6.0.6 on 2026-07-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_name', models.CharField(default='Scale 1', max_length=255)),
                ('scale_status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('ERROR', 'Error')], default='READY', max_length=30)),
                ('tare_update_enabled', models.BooleanField(default=True)),
                ('op_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
        ),
    ]
