# Generated by Django 6.0.6 on 2026-07-13 17:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_id', models.BigIntegerField(blank=True, null=True)),
                ('scale_process_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scale_name', models.CharField(blank=True, max_length=255, null=True)),
                ('weighing_start_date', models.DateTimeField(auto_now_add=True)),
                ('weighing_end_date', models.DateTimeField(blank=True, null=True)),
                ('up_date_time', models.DateTimeField(blank=True, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('actual_tare', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('actual_neto', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('valid_tare', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('valid_neto', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('max_speed', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8)),
                ('min_speed', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8)),
                ('direction', models.CharField(default='OUT', max_length=10)),
                ('layout', models.CharField(blank=True, max_length=255, null=True)),
                ('weighing_method', models.CharField(choices=[('DYNAMIC', 'Dynamic'), ('STATIC', 'Static')], default='DYNAMIC', max_length=30)),
                ('done', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('actual_matched', models.BooleanField(default=False)),
                ('valid_matched', models.BooleanField(default=False)),
                ('numbered', models.BooleanField(default=False)),
                ('over_load', models.BooleanField(default=False)),
                ('over_speed', models.BooleanField(default=False)),
                ('commercial', models.BooleanField(default=False)),
                ('technical_safety', models.BooleanField(default=False)),
                ('video_path_1', models.CharField(blank=True, max_length=500, null=True)),
                ('video_path_2', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-weighing_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Wagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_id', models.BigIntegerField(blank=True, null=True)),
                ('scale_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wagon_type', models.CharField(choices=[('BASIC', 'Basic')], default='BASIC', max_length=30)),
                ('axle', models.IntegerField(default=4)),
                ('wagon_number', models.CharField(blank=True, max_length=20, null=True)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('wagon_description', models.CharField(blank=True, max_length=500, null=True)),
                ('weighing_date', models.DateTimeField(auto_now_add=True)),
                ('product_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('valid_tare', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('actual_tare', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('speed', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=8)),
                ('valid', models.BooleanField(default=False)),
                ('overload', models.BooleanField(default=False)),
                ('over_speed', models.BooleanField(default=False)),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wagons', to='proc.train')),
            ],
            options={
                'ordering': ['row_number'],
                'constraints': [models.UniqueConstraint(fields=('train', 'row_number'), name='unique_train_row'), models.UniqueConstraint(fields=('train', 'wagon_number'), name='unique_train_wagon_number')],
            },
        ),
    ]
