# Generated by Django 6.0.6 on 2026-07-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_no', models.PositiveSmallIntegerField(unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('cam_name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(default='192.168.1.100')),
                ('rtsp_port', models.PositiveIntegerField(default=554)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('rtsp_path', models.CharField(default='/Streaming/Channels/101', max_length=255)),
            ],
            options={
                'ordering': ['camera_no'],
            },
        ),
    ]
