# Generated by Django 6.0.6 on 2026-07-10 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camsettings',
            name='min_confidence',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='camsettings',
            name='rtsp_path',
            field=models.CharField(blank=True, default='/Streaming/Channels/101', max_length=255),
        ),
    ]
