# Generated by Django 6.0.6 on 2026-07-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0002_camsettings_min_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camsettings',
            name='min_height',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='camsettings',
            name='min_width',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
